#!/bin/sh

# Usage: $0
# preview my ~/etc directory

###############################################################################
cd "$HOME/etc"

ansi() { printf '\033[%sm' "$1"; }
HIGH=$(ansi 33)
RESET=$(ansi 0)

is_installed() { #args: PACKAGE
   # returns 0 if package is installed, non-zero otherwise
   which "$1" >/dev/null ||
   apt list --installed 2>/dev/null | grep -q "^$1/"
}
###############################################################################

COLUMNS=$(stty size | cut -f2 -d' ')

#find -maxdepth 1                              |
find ./* -type d -prune                        |
sed -e 's:\./::' -e 's:^\.$::'                 |
while IFS= read -r i; do
   if [ -d "$i" ] && is_installed "$i"
      then printf '%s\n' "${HIGH}${i}${RESET}"
      else printf '%s\n' "$i"
   fi
done                                           |
fzf --ansi                                     \
    --prompt  'etc > '                         \
    --bind 'Alt-Z:toggle-preview'              \
    --preview-window "right:$((COLUMNS - 22))" \
    --preview 'if [ -d {} ]
                  then tree -aFC {}
                  else cat {}
               fi'                             \
    --query "$*"
